# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from FLite.protobuf import (
    client_service_pb2 as FLite_dot_protobuf_dot_client__service__pb2,
)


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Operate = channel.unary_unary(
            "/FLite.protobuf.ClientService/Operate",
            request_serializer=FLite_dot_protobuf_dot_client__service__pb2.OperateRequest.SerializeToString,
            response_deserializer=FLite_dot_protobuf_dot_client__service__pb2.OperateResponse.FromString,
        )


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Operate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Operate": grpc.unary_unary_rpc_method_handler(
            servicer.Operate,
            request_deserializer=FLite_dot_protobuf_dot_client__service__pb2.OperateRequest.FromString,
            response_serializer=FLite_dot_protobuf_dot_client__service__pb2.OperateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "FLite.protobuf.ClientService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Operate(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/FLite.protobuf.ClientService/Operate",
            FLite_dot_protobuf_dot_client__service__pb2.OperateRequest.SerializeToString,
            FLite_dot_protobuf_dot_client__service__pb2.OperateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
